name: Deploy Hexo

on:
  push:
    branches:
      - main  # 只有推送到 main 分支时才触发

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout  # 第一步：把你的源码拉取到 GitHub 的虚拟电脑上
        uses: actions/checkout@v4

      - name: Setup Node # 第二步：在虚拟电脑上安装 Node.js 环境
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies # 第三步：安装 Hexo 及其插件
        run: npm install

      - name: Generate # 第四步：运行 Hexo 生成命令
        run: npx hexo generate

      - name: Deploy # 第五步：将生成的 public 文件夹发布到 Pages
        uses: actions/deploy-pages@v4